import { PolicyLayout, PolicyCallout } from "@/components/policy/PolicyLayout";

const Terms = () => (
  <PolicyLayout
    eyebrow="Legal"
    title="Terms and Conditions of Service"
    version="1.0"
    effective="31 March 2026"
    jurisdictions="Governing law: Republic of Singapore"
  >
    <PolicyCallout tone="danger" title="IMPORTANT NOTICE — PLEASE READ CAREFULLY BEFORE USE">
      <p>This Service uses a QR code-based method to connect to WhatsApp ("WhatsApp Web/Multi-Device Protocol") and does NOT operate through Meta's official WhatsApp Business API. Use of this Service may violate WhatsApp's and Meta's Terms of Service. Your WhatsApp account(s) may be suspended or permanently banned by Meta at any time without notice. By proceeding, you acknowledge and fully accept this risk. The Company provides no guarantee against account suspension and accepts no liability for any resulting business disruption, data loss, or financial loss.</p>
    </PolicyCallout>
    <p>By accessing, registering for, or using the Quicksales.ai Service, you agree to be bound by these Terms and Conditions in their entirety. If you do not agree, you must not use the Service. If you are accepting on behalf of a company or legal entity, you represent that you have the authority to bind that entity.</p>

    <h2>1. Definitions</h2>
    <p>In these Terms and Conditions, the following definitions apply:</p>
    <ul>
      <li><strong>"Company"</strong> means Quicksales.ai, its subsidiaries, affiliates, officers, directors, employees, agents, and licensors.</li>
      <li><strong>"Service"</strong> means the Quicksales.ai platform, including all features, tools, AI agents, automation workflows, web widgets, APIs, and integrations made available to Subscribers.</li>
      <li><strong>"Subscriber"</strong> or <strong>"User"</strong> means any individual or entity that registers for, accesses, or uses the Service under a valid subscription.</li>
      <li><strong>"Subscription"</strong> means the paid plan purchased by the Subscriber to access the Service.</li>
      <li><strong>"User Data"</strong> means all data, content, contacts, messages, files, and information inputted, uploaded, processed, or generated by the Subscriber through the Service.</li>
      <li><strong>"WhatsApp"</strong> means the messaging platform operated by Meta Platforms, Inc. and its affiliates.</li>
      <li><strong>"Meta ToS"</strong> means the Terms of Service, Acceptable Use Policy, and Community Standards published by Meta Platforms, Inc., as amended from time to time.</li>
      <li><strong>"AI Agent"</strong> means the artificial intelligence-powered automated response and workflow agent configured by the Subscriber within the Service.</li>
      <li><strong>"Third-Party Platform"</strong> means any external service, application, or platform (including WhatsApp, Meta, and any integration partner) that the Service connects to or interoperates with.</li>
      <li><strong>"Personal Data"</strong> has the meaning ascribed to it under the Singapore Personal Data Protection Act 2012 (No. 26 of 2012) ("PDPA") and equivalent applicable data protection legislation.</li>
      <li><strong>"Force Majeure Event"</strong> means any event beyond the reasonable control of the Company, including but not limited to natural disasters, war, acts of terrorism, government actions, internet or telecommunications failures, Third-Party Platform policy changes, or acts of God.</li>
    </ul>

    <h2>2. Scope of Service</h2>
    <h3>2.1 Services Provided</h3>
    <p>The Company provides a SaaS platform enabling Subscribers to deploy AI-powered agents on WhatsApp and other channels. Current features include:</p>
    <ul>
      <li>QR code-based WhatsApp account synchronisation and AI agent setup</li>
      <li>Creation and management of multiple AI Agents assignable to different chat threads</li>
      <li>Automated appointment booking and scheduling workflows</li>
      <li>Lead generation tools and contact capture</li>
      <li>Web widget setup for external websites</li>
    </ul>
    <h3>2.2 Features in Development</h3>
    <p>The following features are under development and not yet available. Their release timeline, availability, and final scope are not guaranteed:</p>
    <ul>
      <li>Voice message recognition and transcription</li>
      <li>File reading (PDF and image processing)</li>
      <li>Automated file creation and document generation</li>
      <li>Bulk messaging functionality</li>
      <li>In-platform Customer Relationship Management (CRM)</li>
      <li>Integration Board for third-party platform connections</li>
    </ul>
    <p>The Company reserves the right to modify, delay, cancel, or alter any planned feature at its sole discretion without liability.</p>
    <h3>2.3 Service Standard</h3>
    <p>The Service is provided on an "as-is" and "as-available" basis. The Company does not warrant that the Service will be uninterrupted, error-free, or fit for any particular purpose. No guarantee is made as to message delivery rates, AI Agent response accuracy, lead quality, appointment booking success, or uninterrupted integration with Third-Party Platforms.</p>

    <h2>3. WhatsApp QR Code Synchronisation — Critical Risk Disclosure</h2>
    <PolicyCallout tone="danger" title="MANDATORY ACKNOWLEDGEMENT REQUIRED">
      <p>This section constitutes a material disclosure. Your continued use of the QR code synchronisation feature is your express acknowledgement and acceptance of all risks described herein.</p>
    </PolicyCallout>
    <h3>3.1 Unofficial Integration Method</h3>
    <p>The Service connects to WhatsApp via a QR code scanning mechanism that relies on WhatsApp Web and the Multi-Device protocol. This method is NOT an official Meta-approved integration. It does not use the WhatsApp Business API (Cloud API) or any other Meta-sanctioned developer programme.</p>
    <h3>3.2 Violation of Meta Terms of Service</h3>
    <p>Meta's Terms of Service, WhatsApp Terms of Service, and WhatsApp Business Policy explicitly prohibit:</p>
    <ul>
      <li>Use of automated or bulk messaging through unofficial clients</li>
      <li>Reverse engineering or unauthorised access to WhatsApp services</li>
      <li>Connecting third-party software to WhatsApp without Meta's express authorisation</li>
    </ul>
    <p>The Subscriber acknowledges that using the Service's QR code feature may constitute a violation of the Meta ToS.</p>
    <h3>3.3 Risk of Account Suspension and Ban</h3>
    <p>As a direct and known consequence of Clause 3.2, the Subscriber's WhatsApp account(s) — whether personal or WhatsApp Business App accounts — may be:</p>
    <ul>
      <li>Temporarily suspended or rate-limited by Meta</li>
      <li>Permanently banned and irrecoverably terminated by Meta</li>
      <li>Subject to number-level blocks that cannot be appealed or reversed</li>
    </ul>
    <p>The Company has no ability to and can not prevent, reverse, or appeal any action taken by Meta against a Subscriber's account. The Company provides no warranty or assurance of continued WhatsApp account access.</p>
    <h3>3.4 Subscriber's Acceptance of Risk</h3>
    <p>By using the QR code synchronisation feature, the Subscriber expressly and irrevocably:</p>
    <ul>
      <li>Acknowledges full awareness of the risks described in this Section 3;</li>
      <li>Accepts sole and full responsibility for any consequences arising from Meta's enforcement actions, including permanent account bans;</li>
      <li>Waives any right to claim against the Company for loss of WhatsApp access, business disruption, loss of contacts, loss of chat history, revenue loss, or any other damage arising from Meta's actions;</li>
      <li>Agrees to indemnify the Company against any claim brought by Meta or any third party arising from the Subscriber's use of the QR code feature.</li>
    </ul>
    <h3>3.5 No Liability for Meta Policy Changes</h3>
    <p>Meta may at any time and without notice change its Terms of Service, technical protocols, or enforcement practices in ways that render the Service non-functional or that result in mass account suspensions. The Company accepts no liability for any such changes or their consequences.</p>

    <h2>4. Subscriber Responsibilities and Obligations</h2>
    <h3>4.1 Lawful Use</h3>
    <p>The Subscriber shall use the Service exclusively in compliance with all applicable laws and regulations, including but not limited to:</p>
    <ul>
      <li>Singapore Personal Data Protection Act 2012 (PDPA)</li>
      <li>Singapore Spam Control Act (Cap. 311A)</li>
      <li>EU General Data Protection Regulation (GDPR), where applicable</li>
      <li>Malaysia Personal Data Protection Act 2010, where applicable</li>
      <li>Any other applicable national data protection, anti-spam, or consumer protection legislation</li>
      <li>WhatsApp Terms of Service and Meta Platforms Terms of Service (subject to the disclosures in Section 3)</li>
      <li>All applicable telecommunications regulations in the Subscriber's jurisdiction</li>
    </ul>
    <h3>4.2 Prohibited Conduct</h3>
    <p>The Subscriber must not use the Service to:</p>
    <ul>
      <li>Send unsolicited commercial communications (spam) to individuals who have not provided consent</li>
      <li>Harass, threaten, defame, or abuse any individual or entity</li>
      <li>Collect, process, or transmit Personal Data without a lawful basis or the data subject's consent</li>
      <li>Scrape, harvest, or otherwise collect contact information in violation of applicable law or platform terms</li>
      <li>Disseminate false, misleading, or fraudulent information</li>
      <li>Infringe any intellectual property right of any third party</li>
      <li>Introduce malware, viruses, or malicious code into the Service or any connected platform</li>
      <li>Attempt to circumvent, hack, reverse-engineer, or disrupt the Service or any Third-Party Platform</li>
      <li>Resell, sublicense, or provide access to the Service to unauthorised third parties</li>
      <li>Use the Service in any way that violates applicable law or causes harm to any person</li>
    </ul>
    <h3>4.3 Subscriber's Own Compliance</h3>
    <p>The Subscriber is solely responsible for:</p>
    <ul>
      <li>Obtaining all necessary consents from end-users and contacts before sending any AI-generated or automated communications</li>
      <li>Ensuring that all AI Agent prompts, responses, and workflows comply with applicable law</li>
      <li>Reviewing and approving all AI-generated content before deployment, where required by law</li>
      <li>Maintaining their own compliance programme in relation to data protection and anti-spam obligations</li>
      <li>Keeping their account credentials secure and immediately notifying the Company of any suspected unauthorised access</li>
    </ul>
    <h3>4.4 Accuracy of Information</h3>
    <p>The Subscriber warrants that all information provided to the Company (including registration details, billing information, and business information) is accurate, current, and complete, and shall be promptly updated if it changes.</p>

    <h2>5. Data, Privacy, and Security</h2>
    <h3>5.1 Data Ownership</h3>
    <p>As between the Company and the Subscriber, the Subscriber retains ownership of all User Data. By using the Service, the Subscriber grants the Company a limited, non-exclusive, worldwide, royalty-free licence to access, store, process, and use User Data solely to the extent necessary to provide the Service.</p>
    <h3>5.2 Company's Data Processing Obligations</h3>
    <p>The Company will:</p>
    <ul>
      <li>Process User Data in accordance with these Terms, the Privacy Policy (available at https://quicksales.ai/privacy), and applicable data protection law.</li>
      <li>Implement reasonable technical and organisational security measures designed to protect User Data against unauthorised access, loss, or disclosure.</li>
      <li>Notify the Subscriber as soon as practicable after becoming aware of a confirmed Personal Data breach affecting the Subscriber's data, and in any event within the timelines required by applicable law.</li>
      <li>Not sell User Data and not disclose User Data to third parties except as necessary to provide the Service, as required by law, or with the Subscriber's consent.</li>
    </ul>
    <p>Where the Company processes Personal Data on behalf of the Subscriber, the Company acts as a data intermediary (under the PDPA) and/or data processor (under GDPR or equivalent laws) as applicable, and the Subscriber acts as the organisation and/or controller. Where required, the parties will enter into a separate data processing agreement ("DPA") and implement appropriate cross-border transfer safeguards (including Standard Contractual Clauses or other lawful transfer mechanisms, where applicable).</p>
    <p>The Company may use third-party service providers (each a "Subprocessor") to assist in providing the Service. A list of Subprocessors is available at https://quicksales.ai/subprocessors (or on request). The Company will provide reasonable advance notice of material changes to its Subprocessors by updating the list and/or notifying Subscribers.</p>
    <h3>5.3 Limitation of Liability for Data Breach</h3>
    <p>Notwithstanding Clause 5.2:</p>
    <ul>
      <li>The Company's liability for any and only wilful data breach shall be limited to the greater of: (a) the aggregate Subscription Fees paid by the Subscriber in the six (6) months immediately preceding the breach; or (b) SGD 5,000.</li>
      <li>The Company shall have no liability for any data breach arising from: (i) the Subscriber's own negligence or failure to maintain adequate access controls; (ii) the actions of Meta, WhatsApp, or any Third-Party Platform; (iii) a Force Majeure Event; or (iv) the Subscriber's use of the QR code synchronisation method described in Section 3.</li>
      <li>The Company does not warrant that the Service is invulnerable to attack or that data transmitted via WhatsApp's unofficial API is encrypted or secured to any particular standard.</li>
      <li>The Subscriber acknowledges that data transmitted through WhatsApp via the QR code method may be subject to interception or loss and assumes all associated risk.</li>
    </ul>
    <h3>5.4 Subscriber's Data Security Obligations</h3>
    <p>The Subscriber is responsible for:</p>
    <ul>
      <li>Maintaining the security of their account credentials and access tokens</li>
      <li>Implementing appropriate security measures within their own systems</li>
      <li>Ensuring that any Personal Data processed through the Service is processed lawfully and with appropriate consent</li>
      <li>Promptly reporting to the Company any suspected security incident or breach involving the Service</li>
    </ul>
    <h3>5.5 Data Retention and Deletion</h3>
    <p>Upon termination of the Subscriber's account, the Company will retain User Data for a period of thirty (30) days, after which it may be permanently deleted. The Subscriber is responsible for exporting any required data before termination. The Company is not liable for any data loss following termination. The company will use reasonable endeavours to comply where feasible and where not prohibited by law. The Subscriber remains responsible for exporting any required data before termination or deletion. The Company is not liable for any data loss following termination or deletion.</p>
    <h3>5.6 Cross-Border Data Transfers</h3>
    <p>The Subscriber acknowledges that the Service may involve the transfer and processing of User Data across international borders, including by the Company and its Subprocessors. The Company will take reasonable steps to ensure that overseas recipients of Personal Data under its control are bound by legally enforceable obligations to provide a standard of protection that is comparable to applicable requirements (including under the PDPA), including through contractual safeguards where appropriate.</p>
    <p>The Subscriber remains responsible for ensuring it has a lawful basis to collect, use, and disclose Personal Data to the Company and for any additional transfer requirements that apply to the Subscriber under laws applicable to the Subscriber.</p>

    <h2>6. AI Agents, Automation, and Appointment Booking</h2>
    <h3>6.1 Nature of AI-Generated Content</h3>
    <p>AI Agents deployed through the Service generate responses and content based on prompts configured by the Subscriber and machine learning models. The Company does not warrant that AI-generated content will be:</p>
    <ul>
      <li>Accurate, complete, or up-to-date</li>
      <li>Free from errors, hallucinations, or unintended statements</li>
      <li>Appropriate for the Subscriber's intended use case or industry</li>
      <li>Compliant with applicable law in all jurisdictions</li>
    </ul>
    <h3>6.2 Subscriber Responsibility for AI Output</h3>
    <p>The Subscriber is solely responsible for:</p>
    <ul>
      <li>Configuring AI Agent prompts in a lawful, accurate, and appropriate manner</li>
      <li>Reviewing AI-generated responses before deployment is legally required (including in regulated industries such as financial services, healthcare, and law)</li>
      <li>All communications sent by AI Agents to end-users or contacts, including any misrepresentations or errors therein</li>
      <li>Ensuring that AI Agents do not make false claims, mislead consumers, or violate any applicable law or regulation</li>
    </ul>
    <h3>6.3 Appointment Booking</h3>
    <p>The automated appointment booking feature is provided as a convenience tool only. The Company does not guarantee:</p>
    <ul>
      <li><strong>That appointments will be correctly recorded, confirmed, or fulfilled</strong></li>
      <li><strong>That integrations with third-party calendar or booking systems will function without error</strong></li>
      <li><strong>That end-customers will receive accurate booking confirmations</strong></li>
    </ul>
    <p>The Subscriber assumes full responsibility for verifying the accuracy of all bookings and for managing any disputes arising from booking errors.</p>
    <h3>6.4 Lead Generation</h3>
    <p>The lead generation feature assists in identifying and capturing potential customer information. The Company makes no warranty as to:</p>
    <ul>
      <li><strong>The quality, accuracy, or conversion potential of any leads generated</strong></li>
      <li><strong>The lawfulness of lead capture methods deployed by the Subscriber</strong></li>
    </ul>
    <p>The Subscriber is responsible for ensuring that all lead generation activities comply with applicable data protection and anti-spam laws, including obtaining valid consent where required.</p>

    <h2>7. Service Availability, Downtime, and Support</h2>
    <h3>7.1 Uptime Target</h3>
    <p>The Company will use commercially reasonable efforts to maintain Service availability. The Company targets, but does not guarantee, a monthly uptime of 99% (excluding scheduled maintenance and Force Majeure Events). No service level agreement (SLA) with financial remedies is implied unless explicitly set out in a separate written agreement signed by the Company.</p>
    <h3>7.2 Planned Maintenance</h3>
    <p>The Company reserves the right to perform scheduled maintenance, which may result in temporary Service unavailability. Where practicable, the Company will provide advance notice of scheduled maintenance via the platform or email.</p>
    <h3>7.3 Limitation of Liability for Downtime</h3>
    <p>For these Terms, "Downtime" means a complete inability for the Subscriber to access and use the core features of the Service due to a failure of the Company's systems, excluding (a) scheduled maintenance; (b) Force Majeure Events; (c) issues caused by the Subscriber's internet/networking, devices, or configurations; (d) issues caused by Third-Party Platforms (including WhatsApp/Meta) or third-party integrations; and (e) beta, trial, or development features. The Company shall not be liable for any loss of revenue, profit, business, data loss, or consequential loss arising from Downtime. The Subscriber's sole remedy for Downtime is a pro-rated service credit if the Service experiences Downtime exceeding <strong>24 consecutive hours</strong>. To claim a credit, the Subscriber must submit a support ticket within seven (7) days of the incident. Service credits will be calculated based on the Subscription Fee paid for the affected month and will not exceed the Subscription Fee paid for that month.</p>
    <h3>7.4 Third-Party Platform Downtime</h3>
    <p>The Company is not responsible for downtime, service degradation, or access restrictions caused by any Third-Party Platform, including WhatsApp, Meta, or any integration partner. No refunds or credits will be issued for Service disruption attributable to Third-Party Platform outages.</p>
    <h3>7.5 No Liability for Meta-Initiated Disruption</h3>
    <p>If Meta takes any action (including but not limited to protocol changes, enforcement actions, or API modifications) that disrupts or terminates the Service's ability to connect to WhatsApp, the Company shall not be liable to the Subscriber for any resulting loss. The Company will use reasonable endeavours to restore functionality but does not guarantee restoration within any specified timeframe.</p>

    <h2>8. Payment, Billing, and Refunds</h2>
    <h3>8.1 Subscription Fees</h3>
    <p>Subscriptions are billed in advance on a monthly or annual basis as selected by the Subscriber at the time of purchase. All fees are stated in Singapore Dollars (SGD) or United States Dollars (USD) as indicated on the pricing page, and are exclusive of applicable taxes.</p>
    <h3>8.2 Non-Refundable Fees</h3>
    <p>All Subscription Fees are non-refundable except:</p>
    <ul>
      <li>Where required by mandatory consumer protection law applicable to the Subscriber's jurisdiction</li>
      <li>Where the Company terminates the Subscriber's account without cause, in which case a pro-rated refund for the unused portion of the current Subscription period will be issued</li>
    </ul>
    <p>No refund will be issued on the basis of a WhatsApp account suspension or ban resulting from the use of the QR code synchronization feature.</p>
    <h3>8.3 Taxes</h3>
    <p>The Subscriber is responsible for all applicable taxes, duties, and levies (including Singapore GST where applicable) arising from the Subscription.</p>
    <h3>8.4 Non-Payment</h3>
    <p>Failure to pay Subscription Fees by the due date may result in suspension of access to the Service. Accounts suspended for non-payment for more than thirty (30) days may be terminated, and User Data deleted. The Company reserves the right to charge interest on overdue amounts at the rate of 1.5% per month.</p>
    <h3>8.5 Fee Changes</h3>
    <p>The Company reserves the right to modify Subscription Fees at any time, with at least thirty (30) days' written notice to the Subscriber. Continued use of the Service after the effective date of a fee change constitutes acceptance of the new fees.</p>

    <h2>9. Limitation of Liability</h2>
    <PolicyCallout tone="warning">
      <p>This section is of critical importance. Please read it carefully as it significantly affects your legal rights.</p>
    </PolicyCallout>
    <h3>9.1 Exclusion of Warranties</h3>
    <p>To the maximum extent permitted by applicable law, the Company expressly disclaims all warranties, express or implied, including but not limited to:</p>
    <ul>
      <li>Implied warranties of merchantability, fitness for a particular purpose, and non-infringement</li>
      <li>Any warranty that the Service will meet the Subscriber's requirements</li>
      <li>Any warranty as to the accuracy or reliability of AI-generated content</li>
      <li>Any warranty that the Service will be uninterrupted, error-free, or secure</li>
    </ul>
    <h3>9.2 Cap on Liability</h3>
    <p>To the fullest extent permitted by law, the Company's total aggregate liability to the Subscriber for all claims arising out of or in connection with these Terms or the Service — whether in contract, tort (including negligence), breach of statutory duty, or otherwise — shall not exceed the total Subscription Fees paid by the Subscriber in the twelve (12) months immediately preceding the event giving rise to the claim.</p>
    <h3>9.3 Exclusion of Consequential Loss</h3>
    <p>In no event shall the Company be liable for:</p>
    <ul>
      <li>Loss of profits, revenue, or anticipated savings</li>
      <li>Loss of business, contracts, or goodwill</li>
      <li>Loss of data or information</li>
      <li>Business interruption or loss of business opportunity</li>
      <li>Indirect, special, incidental, exemplary, punitive, or consequential damages of any kind</li>
    </ul>
    <p>The above exclusions apply regardless of whether the Company was advised of the possibility of such loss.</p>
    <h3>9.4 Specific Exclusions</h3>
    <p>Without limiting the foregoing, the Company shall have no liability whatsoever for:</p>
    <ul>
      <li>Suspension, banning, or restriction of the Subscriber's WhatsApp account(s) by Meta or WhatsApp</li>
      <li>Loss of WhatsApp contacts, chat history, or data resulting from a Meta-initiated account ban</li>
      <li>Business disruption arising from the Subscriber's inability to use WhatsApp following a ban</li>
      <li>Actions taken by any Third-Party Platform, including changes to APIs, protocols, or terms</li>
      <li>Any data breach, loss, or misuse arising from the Subscriber's own negligence or that of a Third-Party Platform</li>
      <li>Errors, inaccuracies, or unintended content generated by AI Agents</li>
      <li>Failure of automated appointment booking or lead generation functions to meet business expectations</li>
      <li>Any loss arising from a Force Majeure Event</li>
    </ul>
    <h3>9.5 Exceptions</h3>
    <p>Nothing in these Terms shall limit or exclude the Company's liability for:</p>
    <ul>
      <li>Death or personal injury caused by the Company's negligence</li>
      <li>Fraud or fraudulent misrepresentation</li>
      <li>Any liability that cannot be excluded or limited by applicable Singapore law</li>
    </ul>

    <h2>10. Indemnification</h2>
    <h3>10.1 Subscriber's Indemnity</h3>
    <p>The Subscriber agrees to indemnify, defend, and hold harmless the Company, its affiliates, officers, directors, employees, agents, and licensors from and against any and all claims, demands, proceedings, losses, damages, costs, penalties, fines, and expenses (including reasonable legal fees) arising out of or in connection with:</p>
    <ul>
      <li>Any breach by the Subscriber of these Terms</li>
      <li>The Subscriber's use of the Service, including any AI Agent configuration and communications sent</li>
      <li>Any violation by the Subscriber of applicable law, including data protection, anti-spam, and consumer protection law</li>
      <li>Any violation by the Subscriber of the Meta ToS, WhatsApp Terms of Service, or any other Third-Party Platform terms</li>
      <li>Any claim by an end-user, contact, or data subject arising from communications sent by or on behalf of the Subscriber through the Service</li>
      <li>Any claim by Meta or WhatsApp arising from the Subscriber's use of the QR code synchronisation feature</li>
      <li>Any third-party claim arising from User Data processed through the Service</li>
    </ul>
    <h3>10.2 Indemnification Process</h3>
    <p>The Company will promptly notify the Subscriber of any claim subject to indemnification, cooperate reasonably in the defence of such claim, and allow the Subscriber to control the defence, provided that the Company may participate in the defence with its own counsel at its own expense. The Subscriber may not settle any claim in a manner that imposes obligations on the Company without the Company's prior written consent.</p>

    <h2>11. Intellectual Property</h2>
    <h3>11.1 Company's IP</h3>
    <p>The Company owns all right, title, and interest in and to the Service, including all software, AI models, machine learning systems, workflows, designs, documentation, trademarks, and trade secrets. Nothing in these Terms transfers any ownership of the Company's intellectual property to the Subscriber.</p>
    <h3>11.2 Restrictions</h3>
    <p>The Subscriber shall not:</p>
    <ul>
      <li>Copy, reproduce, distribute, or create derivative works based on the Service</li>
      <li>Reverse-engineer, decompile, disassemble, or attempt to extract the source code of the Service</li>
      <li>Resell, sublicense, transfer, or make the Service available to any third party without the Company's written consent</li>
      <li>Remove or alter any proprietary notices, labels, or marks on the Service</li>
    </ul>
    <h3>11.3 Subscriber's IP and Licence</h3>
    <p>The Subscriber retains all intellectual property rights in User Data. The Subscriber grants the Company a limited, non-exclusive, royalty-free licence to access, host, store, process, transmit, and use User Data solely to the extent necessary to provide, maintain, and secure the Service and to perform the Company's obligations under these Terms.</p>
    <p>The Company may use Aggregated and Anonymized Data to improve and develop the Service, including to improve automation and AI features, provided that such data does not reasonably identify the Subscriber or any individual. "Aggregated and Anonymized Data" means data that has been combined with other data and processed to remove personal identifiers such that individuals are not reasonably identifiable.</p>
    <p>If the Company offers an opt-out for certain plans, the Subscriber may opt out of such use by contacting Support@quicksales.ai or via in-platform settings (if available).</p>

    <h2>12. Term, Suspension, and Termination</h2>
    <h3>12.1 Term</h3>
    <p>These Terms commence on the date the Subscriber first accesses the Service and continue until terminated by either party in accordance with this Section.</p>
    <h3>12.2 Termination by Subscriber</h3>
    <p>The Subscriber may terminate their Subscription at any time by providing written notice to the Company. Termination will take effect at the end of the then-current Subscription billing period. No refund will be issued for any unused portion of a prepaid Subscription except as provided in Clause 8.2.</p>
    <h3>12.3 Suspension or Termination by the Company</h3>
    <p>The Company may suspend or terminate the Subscriber's access to the Service if the Subscriber breaches these Terms or if the Company reasonably believes suspension or termination is necessary to protect the Service, other subscribers, or third parties, or to comply with applicable law.</p>
    <p>Where a breach is capable of cure, the Company will use reasonable endeavours to provide notice and a reasonable opportunity to cure before termination. However, the Company may suspend access immediately and without prior notice where it reasonably considers it necessary to prevent harm, comply with law, respond to security incidents, address suspected fraud or abuse, or mitigate material risk to the Service, other subscribers, or third parties.</p>
    <p>Without limiting the above, the Company may suspend or terminate if:</p>
    <ul>
      <li>The Subscriber breaches any provision of these Terms;</li>
      <li>The Subscriber engages in conduct that the Company reasonably believes constitutes illegal activity;</li>
      <li>The Subscriber's use of the Service poses a risk to the Company, other subscribers, or third parties;</li>
      <li>The Company is required to do so by applicable law, court order, or regulatory requirement; or</li>
      <li>The Subscriber fails to pay Subscription Fees when due.</li>
    </ul>
    <p>The Company will use reasonable endeavours to notify the Subscriber of any suspension, but is not obligated to do so before acting where immediate action is required.</p>
    <h3>12.4 Effect of Termination</h3>
    <p>Upon termination:</p>
    <ul>
      <li>All rights granted to the Subscriber under these Terms cease immediately</li>
      <li>The Subscriber must immediately cease all use of the Service</li>
      <li>User Data will be retained for thirty (30) days and then permanently deleted</li>
      <li>The Company is not liable for any data loss, business disruption, or other consequence of termination</li>
      <li>Provisions that by their nature should survive termination (including Sections 5, 9, 10, 11, and 14) shall do so</li>
    </ul>

    <h2>13. Third-Party Integrations and Services</h2>
    <p>The Service may integrate with or connect to Third-Party Platforms. The Company:</p>
    <ul>
      <li>Does not endorse, control, or take responsibility for any Third-Party Platform</li>
      <li>Does not guarantee the availability, functionality, or security of any Third-Party Platform</li>
      <li>Is not liable for any loss arising from the Subscriber's use of or reliance on a Third-Party Platform</li>
    </ul>
    <p>The Subscriber is solely responsible for complying with the terms of service of any Third-Party Platform used in connection with the Service. Changes to Third-Party Platform terms or technical protocols that affect the Service do not entitle the Subscriber to a refund or any form of compensation.</p>

    <h2>14. Governing Law and Dispute Resolution</h2>
    <h3>14.1 Governing Law</h3>
    <p>These Terms are governed by and construed in accordance with the laws of the Republic of Singapore, without regard to its conflict of law principles.</p>
    <h3>14.2 Mediation</h3>
    <p>In the event of a dispute arising out of or in connection with these Terms, the parties shall first attempt to resolve the dispute through good-faith negotiation. If the dispute is not resolved within thirty (30) days, either party may refer the dispute to mediation administered by the Singapore Mediation Centre (SMC) before commencing arbitration or litigation.</p>
    <h3>14.3 Arbitration</h3>
    <p>If mediation is unsuccessful, any dispute, controversy, or claim arising out of or in connection with these Terms, including any question regarding their existence, validity, or termination, shall be referred to and finally resolved by arbitration administered by the Singapore International Arbitration Centre (SIAC) in accordance with the Arbitration Rules of the SIAC for the time being in force. The seat of arbitration shall be Singapore. The language of arbitration shall be English. The decision of the arbitrator shall be final and binding on both parties.</p>
    <h3>14.4 Injunctive Relief</h3>
    <p>Notwithstanding Clause 14.3, either party may seek urgent injunctive or other equitable relief from a court of competent jurisdiction to prevent irreparable harm, without first undergoing mediation or arbitration.</p>
    <h3>14.5 International Subscribers</h3>
    <p>Where the Subscriber is located outside Singapore, the Subscriber acknowledges and agrees that Singapore law governs these Terms. The Subscriber waives any right to object to Singapore as the jurisdiction for dispute resolution. Where mandatory consumer protection laws in the Subscriber's jurisdiction provide rights that cannot be waived by contract, those rights are not affected.</p>

    <h2>15. Changes to These Terms</h2>
    <p>The Company reserves the right to modify these Terms at any time. Material changes will be notified to the Subscriber via email or in-platform notice at least fourteen (14) days before taking effect. Continued use of the Service after the effective date of any change constitutes the Subscriber's acceptance of the revised Terms. If the Subscriber does not accept the revised Terms, they may terminate their Subscription before the effective date.</p>

    <h2>16. General Provisions</h2>
    <h3>16.1 Entire Agreement</h3>
    <p>These Terms, together with the Company's Privacy Policy and any Order Form or Subscription confirmation, constitute the entire agreement between the parties with respect to the Service and supersede all prior agreements, representations, and understandings.</p>
    <h3>16.2 Severability</h3>
    <p>If any provision of these Terms is found to be invalid, unlawful, or unenforceable by a court of competent jurisdiction, that provision shall be deemed modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force and effect.</p>
    <h3>16.3 Waiver</h3>
    <p>The Company's failure to enforce any right or provision of these Terms shall not constitute a waiver of that right or provision.</p>
    <h3>16.4 Assignment</h3>
    <p>The Subscriber may not assign or transfer any rights or obligations under these Terms without the Company's prior written consent. The Company may freely assign these Terms, including in connection with a merger, acquisition, or sale of assets.</p>
    <h3>16.5 Force Majeure</h3>
    <p>The Company shall not be liable for any failure or delay in performance of its obligations under these Terms to the extent caused by a Force Majeure Event. The Company will use reasonable endeavours to minimise the impact of any Force Majeure Event.</p>
    <h3>16.6 Notices</h3>
    <p>All notices under these Terms shall be in writing. Notices to the Subscriber may be sent to the Subscriber's registered email address and/or by in-platform notice and will be deemed received when sent (unless the sender receives a delivery failure notice).</p>
    <p>Notices to the Company must be sent to <strong>Support@quicksales.ai</strong> and may also be sent to the Company's registered business address. Notices to the Company will be deemed received when the Company acknowledges receipt by email, or two (2) business days after sending by email to <strong>Support@quicksales.ai</strong>, unless the sender receives a delivery failure notice.</p>
    <h3>16.7 No Partnership</h3>
    <p>Nothing in these Terms creates a partnership, joint venture, employment, agency, or franchise relationship between the parties.</p>
    <h3>16.7 Order of Precedence</h3>
    <p>If there is any conflict or inconsistency between documents forming part of the agreement between the Company and the Subscriber, the following order of precedence applies (highest first): (a) any Order Form or written subscription confirmation; (b) any DPA; (c) any separate SLA signed by the Company (if any); (d) these Terms; (e) any Acceptable Use Policy (if published); and (f) the Privacy Policy. For the avoidance of doubt, the Privacy Policy describes the Company's privacy practices and does not override commercial or legal terms unless expressly stated.</p>

    <PolicyCallout tone="info" title="SUBSCRIBER ACKNOWLEDGEMENT">
      <p>By clicking "I Agree", registering for an account, or using the Service, the Subscriber confirms that they have read, understood, and agree to be bound by these Terms and Conditions in their entirety, including the critical risk disclosures in Section 3 regarding the QR code-based WhatsApp integration method.</p>
      <p>If accepting on behalf of a company or other legal entity, the Subscriber represents and warrants that they have the authority to bind that entity to these Terms.</p>
    </PolicyCallout>

    <p className="text-sm text-muted-foreground">© 2026 Quicksales.ai. All Rights Reserved.<br/>This document is confidential and proprietary to Quicksales.ai.</p>
  </PolicyLayout>
);

export default Terms;
